### ISSUE TITLE
Integration tests for tcp properties

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom#128]
The lovely tcp-socket integration tests are here: 
https://github.com/freedomjs/freedom/blob/master/spec/providers/coreIntegration/tcpsocket.integration.src.js

We should add tests for the specification of our tcp provider, in particular I think we want these additional tests: 
 * [x] It should be possible to close a socket and once the close promise completes to open a new socket on the same port. 
 * [x] Calling "close" should result in an `onDisconnect` event being fired.
 * [x] Remote closing of the tcp socket should result in an `onDisconnect` event being fired. 
 * [x] Calling `secure` on a closed socket should result in the appropriate failed promise/error. 
 * [x] Calling `write` on a closed socket should result in the appropriate failed promise/error. 
 * [x] Calling `listen` on a socket that is already allocated should result in the appropriate failed promise/error. 
 * [x] Calling `getInfo` on a closed socket should result in the appropriate failed promise/error.
 * [x] The promise from calling `close` should fulfill for a socket that is connected, and should fail appropriately for a socket that is already closed. 
 * [x] Sending data from one socket results in an `onData` event on the other socket. 
 * [x] After calling listen, and before an `onDisconnect` event happen, a connection to the listening socket should result on an `onConnection` event.
 * [x] For a dynamically created socket (a tcp connection made to a listening socket) that is made for an onConnection event: 
  * [x] If the connecting tcp session is still active, creating a new socket object with the id from the `onConnection` event successfully creates a new tcp socket object.  
  * [x] If the connecting tcp session is still active, and a new socket object is made for it, data sent to the dynamic socket results in an `onData` event with the data. 
  * [x] If the connecting tcp session is closed, and a new socket object is made for it, an `onDisconnect` event is fired immidiately.
  * [x] If the connecting tcp session is closed, and a new socket object is made for it, a write event made before the onDisconnect event results in the appropriate error.
 * [x] Data send to a socket after listening happens should get sent to the socket that was created.

**Comment by soycode** [comment]
Revisiting this - the first two suggested tests should be resolved by https://github.com/freedomjs/freedom/commit/e0962302b12c398e786add22395b79b44c6870eb

I am a little uncertain about "Calling getInfo on a closed socket should result in the appropriate failed promise/error." - right now getInfo works on closed sockets, just returns undefined for info.localPort and other data. I went ahead and added an expect to verify that this is the case, but if we should actually be providing a more explicit error then that'll mean changing the implementations not the tests.

In any case, I'll look to add a few more tests for the other suggestions. Thoughts welcome, particularly re: getInfo - thanks!

**Comment by soycode** [comment]
More tests written, progress summarized in #241.

**Comment by soycode** [comment]
Questions about the remaining tests:

- `If the connecting tcp session is closed, and a new socket object is made for it, an onDisconnect event is fired immediately.` - I assume "connecting" means client socket, but I'm not sure what "it" is - do you mean a new socket object is made overwriting the previous client after it is closed? If so, how does this onDisconnect behavior change from the regular onDisconnect behavior? (I thought that onDisconnect just fired whenever a socket disconnected, and making a new socket object doesn't enter into it.)
- `If the connecting tcp session is closed, and a new socket object is made for it, a write event made before the onDisconnect event results in the appropriate error.` - similar to prior. I'm guessing the crux of my misunderstanding is the nature of this new socket object and what calls are being made with it versus with the prior socket.

Thanks!

**Comment by iislucas** [comment]
lets see these were written a while ago... 

The freedom TCP library allows creation of a new freedom socket object given an existing ID (https://github.com/freedomjs/freedom/blob/master/interface/core.tcpsocket.json#L8) for a socket. I think these suggested tests are getting at the need to define failure semantics for when you create a freedom socket object for a closed socket. It might be better to have an error now I think about it. But I haven't thought much about the async nature of this stuff. It's possible for a create call to happen on a socket id that was closed... hopefully ids are not reused otherwise things would get even more confusing. We probably need to specify that ids will not be re-used. 

Make any more sense? if not, lets jump on a hangout tomorrow!

**Comment by soycode** [comment]
Makes sense, it looks like the receiver socket in some of the existing tests is related to this. I should have the remaining tests written and the pull request ready for review shortly.
