### ISSUE TITLE
Design core.xhr provider

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom#136]
We should propose and document what the interface is for xhr (and maybe jsonp) external requests. In particular, can they (& the existing core.websocket permission) be limited at a host level?
Likewise, what is the API, in terms of setting headers and the like - and are the jsonp and xhr one interface or two?

**Comment by ryscheng** [comment]
This has been dealt with

https://github.com/freedomjs/freedom/pull/188
https://github.com/freedomjs/freedom-for-chrome/pull/53
https://github.com/freedomjs/freedom-for-firefox/pull/44
https://github.com/freedomjs/freedom-for-node/pull/23
