### ISSUE TITLE
Update webrtc peerconnection to use core.rtcpeerconnection

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom#152]
Doing so will deprecate:
#80
#67
#66
#50
#13
#10
#9

**Comment by ryscheng** [comment]
https://github.com/freedomjs/freedom/issues/243

**Comment by soycode** [comment]
Looks to still be relevant - is the goal to remove https://github.com/freedomjs/freedom/blob/master/providers/core/core.peerconnection.js completely, or provide a shim that still satisfies its interface but does so by relying on https://github.com/freedomjs/freedom/blob/master/providers/core/core.rtcpeerconnection.js?

**Comment by soycode** [comment]
Very simple related change - https://github.com/freedomjs/freedom/compare/soycode-peerconnection

Just makes core.peerconnection depend on the webrtc-adapter fill, which is also what core.rtcpeerconnection depends on. I'm not sure if it actually resolves all the related issues, but I do think it's an improvement over the old logic and may resolve some things. Thoughts welcome.
