### ISSUE TITLE
Fix core.udpsocket integration test

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom#155]
Currently the udpsocket integration test is really unstable. If it is not run as the last test, it will cause the next test to fail. 
https://github.com/freedomjs/freedom/blob/master/spec/providers/coreIntegration/udpsocket.integration.src.js

I think there's 2 improvements off the top of my head
- We should remove as many setTimeouts as possible and minimize use of it
- done() should only ever be called once within a single test. If it is called multiple times, it'll fail an unrelated test that happens to run next.

**Comment by bemasc** [comment]
For posterity, the setting is called `keepBrowser`.
