### ISSUE TITLE
core.tcpsocket integration tests are buggy

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom#180]
These pull requests are blocked on failing core.tcpsocket integration tests that were added after freedom v0.6.11
https://github.com/freedomjs/freedom-for-node/pull/20
https://github.com/freedomjs/freedom-for-chrome/pull/50
https://github.com/freedomjs/freedom-for-firefox/pull/39

**Comment by willscott** [comment]
TCP sockets are stabilized across all 3 repos from my current snapshot. Feel free to re-open if you notice flakiness, or ideally lets get specific issues in the downstream repos / tests that are failing.

**Comment by iislucas** [comment]
Still seems to be broken according to jenkins:

http://130.211.117.225:8080/

@klazizpro  what's happening ? :)

On Wed, Jan 21, 2015 at 2:07 PM, Will <notifications@github.com> wrote:

> TCP sockets are stabilized across all 3 repos from my current snapshot.
> Feel free to re-open if you notice flakiness, or ideally lets get specific
> issues in the downstream repos / tests that are failing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freedomjs/freedom/issues/180#issuecomment-70900349>.
>



-- 
Lucas Dixon | Google Ideas
