### ISSUE TITLE
pgp API integration tests

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom#186]
https://github.com/freedomjs/freedom-pgp-e2e/blob/master/src/pgpapi.json

**Comment by willscott** [comment]
This is quite close to what the demo is, yes? it's just a matter of making sure that it can be run fully automatically.

**Comment by soycode** [comment]
Yeah agreed, shouldn't be a significant change.

**Comment by soycode** [comment]
Closing as duplicate of https://github.com/freedomjs/freedom-pgp-e2e/issues/6
