### ISSUE TITLE
freedom.js tutorial

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom#187]
Creating a meta issue to track progress of our tutorial
Current plan is to update our Wiki pages with tutorial content
https://github.com/freedomjs/freedom/wiki

Paired with a repository with branches at specific stages of the tutorial 
Location TBD

Fun facts:
Interesting article on how GitHub publishes its documentation using GitHub Pages
https://github.com/blog/1939-how-github-uses-github-to-document-github

**Comment by soycode** [comment]
Main components:

- https://github.com/freedomjs/tutorial
- https://github.com/freedomjs/freedom-starter
- https://github.com/freedomjs/generator-freedom
- https://github.com/soycode/dorabella
