### ISSUE TITLE
freedom().providePromise() should convert exceptions to rejections

### ISSUE THREAD

**Issue by bemasc** [freedomjs/freedom#193]
If a freedom provider, written in the Promise style, contains a bug that results in a method throwing an exception, the caller will never see that exception.  The caller will simply observe that the returned Promise never resolves.

It would be much easier to debug these kinds of problems if Freedom would catch the error and provide an indication of the error to the caller.  The most obvious way to do this would be to make the Promise reject, with a value that indicates the error message and stack.  Alternatively, freedom could pass a representation of the error across the module boundary and reconstitute+rethrow it on the client side.

Without this capability, when writing tests I have taken to wrapping all freedom method bodies in huge try-catch blocks to avoid losing this valuable debugging information.

**Comment by willscott** [comment]
This will only work when the method throws an error in the direct synchronous method, right? or should we just reject immediately if the method doesn't actually return something that looks like a promise?

**Comment by bemasc** [comment]
Yes, I think this is only for exceptions that are thrown synchronously.  Exceptions that are thrown asynchronously will hopefully be inside a Promise chain, and will therefore trigger a rejection as desired.

**Comment by bemasc** [comment]
Also, I agree that freedom should reject if the method returns `undefined` (and does not throw an exception).

**Comment by willscott** [comment]
Added here: https://github.com/freedomjs/freedom/commit/a5eae4f4cb7b9009ce6b1c1935f0a750588a3f08

Will get a test for it before pull-requesting.

**Comment by iislucas** [comment]
I'd suggest that when a freedom API function is not intended to return
something (has no return value in the json API spec), then the freedom stub
interface to the module also does not return (rather than returning a
promise at all).

On Thu, Jan 15, 2015 at 2:20 PM, Will <notifications@github.com> wrote:

> Added here: a5eae4f
> <https://github.com/freedomjs/freedom/commit/a5eae4f4cb7b9009ce6b1c1935f0a750588a3f08>
>
> Will get a test for it before pull-requesting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freedomjs/freedom/issues/193#issuecomment-70144354>.
>



-- 
Lucas Dixon | Google Ideas

**Comment by willscott** [comment]
That's a different issue and out of scope for this bug.

**Comment by iislucas** [comment]
Good point; filed here: https://github.com/freedomjs/freedom/issues/194
