### ISSUE TITLE
Allow synchronous creation of loggers

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom#196]
At the moment (freedom 0.6), to get a logger, you have to do something like this: 
```
var logger;
// Create a logger for this module.
freedom.core().getLogger('[MyModule]').then(function (log) {
  logger = log;
  logger.log('MyModule Logger Instantiated');
});

// ... 
// Note: logger.warn must only be called after the `freedom.core().getLogger`
// promise has resolved, otherwise `logger` will be undefined. 
  logger.warn(msg);
```

As well as being a little inconvenient, the core logging provider is not available when a module's main JS code gets executed.

It would be better if logging was provided synchronously instead of asynchronously. 

e.g. the above should be writable as: 

```
logger = freedom.makeLogger('[MyModule]');
logger.log('blah blah blah');
```

I think this can be done by a simple buffering layer that does the promise work for you in the module environment provided by freedom.

**Comment by willscott** [comment]
That buffering layer is basically what is provided by https://github.com/uProxy/uproxy-lib/tree/dev/src/logging, right?

**Comment by iislucas** [comment]
Yes, that's right.

On Sat, Jan 17, 2015 at 5:54 PM, Will <notifications@github.com> wrote:

> That buffering layer is basically what is provided by
> https://github.com/uProxy/uproxy-lib/tree/dev/src/logging, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freedomjs/freedom/issues/196#issuecomment-70388124>.
>



-- 
Lucas Dixon | Google Ideas
