### ISSUE TITLE
Document `freedom()` object and what happens when you call `provideSynchronous` on it

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom#206]
Maybe in here: 
https://github.com/freedomjs/freedom/wiki/freedom.js-structure:-Provider-Interface

**Comment by willscott** [comment]
First of the three styles listed under the 'Asynchronous Methods' heading:
https://github.com/freedomjs/freedom/wiki/freedom.js-structure:-Provider-Interface#asynchronous-methods

**Comment by willscott** [comment]
After discussion, i believe this is confusion about the current state of the ```default``` key, which will be cleaned up per #204
