### ISSUE TITLE
Update integration tests to be consumed by outside repos

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom#215]

**Comment by willscott** [comment]
What sort of functionality does this bug track? It's not the test infrastructure, but the actual tests that should be able to be run? what needs to be done for that?

**Comment by ryscheng** [comment]
We used to export utilities off of our gruntfile to facilitate running the
integration tests from another repo. E.g. freedom-storage-dropbox

Since the v0.6 redactor to use browserify, this has disappeared. Granted,
it should be much easier now since we can just call freedom(provider), but
the tests need to be rewritten to support this mode of loading.

My radiatus-providers redactor is blocking on this.

**Comment by ryscheng** [comment]
Tracking on https://github.com/freedomjs/freedom/tree/ryscheng-test

**Comment by ryscheng** [comment]
Doneso https://github.com/freedomjs/freedom/pull/220
