### ISSUE TITLE
Expose pause/resume on TCP sockets for flow control

### ISSUE THREAD

**Issue by bemasc** [freedomjs/freedom#233]
Currently there is no way to create backpressure in freedom TCP sockets

**Comment by willscott** [comment]
Seems reasonable. Only point is to make sure we document a clear set of semantics about ordering of these.  Does the `pause` promise resolve only once there are no outstanding calls to send / read? How much is buffered while paused? how are underlying disconnects while paused exposed?

**Comment by bemasc** [comment]
This is done.
