### ISSUE TITLE
Include info of parent manifest when referenced dependency fails

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom#235]
It would be nice to have more details when a module file fails to be found, e.g. here's an error I had recently:

![image](https://cloud.githubusercontent.com/assets/415450/6365940/924807a8-bc8c-11e4-81c8-bccd5c8655e6.png)

There were several different places that may have had the failed path and it would have been awesome if it told me the path to the freedom manifest that had badly referenced file.

**Comment by willscott** [comment]
renamed to; `Include info of parent manifest when referenced dependency fails` for clarity
