### ISSUE TITLE
Descriptive WebWorker names

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom#236]
Right now all WebWorkers have the same name ("freedom.js" or "freedom-for-chrome.js"), at least when trying to inspect them via Chrome dev console. It'd be nice to have more descriptive names of what freedom module they are running.

Workers are made here: https://github.com/freedomjs/freedom/blob/9fef64ed774570057271fbfde6122f2fda3de3b1/src/link/worker.js#L77

And note that this *does* include module name (e.g. the result will be "freedom.js#Module"), but for whatever reason that doesn't change the worker name.

@iislucas suggested checking out if using a blob could help - we seem to already do so for iframes (https://github.com/freedomjs/freedom/blob/9fef64ed774570057271fbfde6122f2fda3de3b1/src/link/frame.js#L142). WebWorkers can be made from blobs, however I'm not sure if putting freedom.js in a blob rather than loading it directly is something we want to do (and I'm also not sure that the blob will result in that much nicer worker names).

In any case, I wanted to document this issue here to not forget it, as whatever the solution it would facilitate debugging. Part of me leans towards thinking that we already are initializing the worker in a clear way (the "freedom.js#Module" thing), so maybe this is ultimately a request for the browser.

**Comment by willscott** [comment]
We purposefully have stopped using blobs. They are much less debuggable - since you get a new one on each page load, meaning that breakpoints do not persist over time.  Tooling at this point means that you can put breakpoints in files and the correct worker will be paused, assuming that you have different client scripts in each module.

We could consider filing chrome bugs to ask for better disambiguation of workers in their developer tools, but I think we're doing everything we can at the moment.

**Comment by iislucas** [comment]
We should definitely find a way to allow naming of web-workers in Chrome / for the spec. But that might not be super quick to land. @willscott are you confident that http://www.html5rocks.com/en/tutorials/file/filesystem/ doesn't allow us the best of both worlds? I haven't experimented, but I would expect persistent storage to have persistent breakpoints. If it doesn't, I think we should file a second issue.

**Comment by willscott** [comment]
Unfortunately filesystem is deprecated and being removed (per the alert at
the top of that link) iirc

**Comment by iislucas** [comment]
The red notice says it is not part of the HTML spec, but I don't see anything to suggest that it's being removed from chrome... ? 

Either way, sounds like it might be worth an experiment as it might work for us at least in the stop-gap until we can get better management of web-workers into Chrome?

**Comment by willscott** [comment]
I believe @mollyling found a chrome bug underlying this, yes?

**Comment by mollyling** [comment]
Update: someone's implemented a fix: https://codereview.chromium.org/1025983002, up for review now.

**Comment by mollyling** [comment]
https://code.google.com/p/chromium/issues/detail?id=466205  Fix submitted.
