### ISSUE TITLE
portType documentation is out of date (or portType is broken)

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom#238]
In https://github.com/freedomjs/freedom/wiki/Debugging-Script-Parse-Errors
It says we can set portType to frame. I just tried this in freedom-for-chrome and it still created everything in WebWorkers. I did a search in freedom source for for `portType`, but didn't find anything. I guess this has been changed and docs fell behind?

**Comment by willscott** [comment]
I believe this works in freedom iirc (and continues to be used there for
unit testing by phantomjs), but not in the downstream freedom-for-chrome
 repo.

**Comment by iislucas** [comment]
Oh, in that case we're printing misleading error messages... 
```
 [Module Churn pipe] E [Feb 28 16:40:02.701] If the stack trace is not useful, see https://github.com/freedomjs/freedom/wiki/Debugging-Script-Parse-Errors
```
:)

**Comment by iislucas** [comment]
(Would be awesome if it worked in freedom-for-chrome)
(Thanks for crazy fast reply!)

**Comment by soycode** [comment]
Re: portType, looks like that is still current: https://github.com/freedomjs/freedom/search?utf8=%E2%9C%93&q=portType

Re: the "If the stack trace is not useful" error message, I agree that we return that error a bit too enthusiastically/generally (as in I've seen it at irrelevant times too). I think just returning the more general https://github.com/freedomjs/freedom/wiki/Debugging instead (and then actually populating that with more useful info) makes sense.

**Comment by soycode** [comment]
https://github.com/freedomjs/freedom/commit/ed27f94bbb93db605680fece744658a4e1427e6c
