### ISSUE TITLE
transport.webrtc - Migrate to using core.rtcpeerconnection

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom#244]
Currently we cannot remove core.peerconnection because the transport.webrtc provider uses it.
We should move the chunking and data channel logic out into transport.webrtc and use core.rtcpeerconnection.

When this is done, this would be a good time to address this as well
https://github.com/freedomjs/freedom/issues/243

**Comment by willscott** [comment]
Dup of #152
