### ISSUE TITLE
Video chat?

### ISSUE THREAD

**Issue by poshetz** [freedomjs/freedom#250]
Hello, i was looking for a video chat solution and i can't understand if is possible through this awesome lib.

Can i create a video chat that works on all browsers using freedom.js?
Also i can't understand... how do you handle the p2p connection? webrtc, websockets, sip or what? 
Can you please clarify it to me, in case i want to use it for a public web video chat  what should i be aware of?

Thanks !

**Comment by ryscheng** [comment]
Great question:
It is certainly possible to build this. You'll want to design your UI and use WebRTC to create the video streams. When you're ready to establish a video chat, you'll want to use our social API to exchange the signaling information between peers. The chat demo is a great place as a point of reference on how to use the social API.

Let us know if you have any other questions. We look forward to your app and please point us to the repo when you're done

Cheers!

**Comment by poshetz** [comment]
@ryscheng  Hi thank you a lot for explaining, could you just explain to me how do you handle media streams, cause you know, video streams are very big usually and you need fast relaying or video from the other side will be not good.

Also, please, are there limits and usage quotas for your API?

**Comment by ryscheng** [comment]
http://www.html5rocks.com/en/tutorials/webrtc/basics/

This tutorial gives a great explanation of WebRTC. When you get to the part that involves exchanging offers, answers, and ice candidates, that's what you'll want to use our Social API for.

**Comment by poshetz** [comment]
@ryscheng  awesome! thank you, and then how the stream goes from one ip to the other? sorry but i am really interested to try something out at this point... let me know please if you can :+1:

**Comment by soycode** [comment]
@poshetz yes, in the chat demo are using ws://p2pbr.com as a provider for our Social API. The actual code for that server is here: https://github.com/freedomjs/socialrouter

All the social provider really has to handle is listing users and enabling them to exchange messages (to set up the actual WebRTC videostream, for your use case). So it doesn't have to deal with the huge size of the videostream, that will be purely peer-to-peer (a nice cost-saving benefit of decentralized services). That said, the social provider still has to scale with # of users, and the scalability of this particular provider isn't great (was just meant for the demo apps).

But really, the nice thing about freedom.js is you can code your app to our Social API and implement or plug in different social providers later (potentially even let your users pick amongst them). You can see our social API here: https://github.com/freedomjs/freedom/blob/master/interface/social.json

And the chat demo you're already checking out is a good illustration of it in action. Additionally, I'm currently working on a tutorial for freedom.js that may help answer some of your questions. Its not complete yet, but you can feel free to check it out - http://www.freedomjs.org/tutorial/ - and if you have any feedback or questions you can file them as issues in the tutorial repository (https://github.com/freedomjs/tutorial).

So, brief summary:
- To write a videochat app you'll want to use WebRTC for the actual videostreaming and our social API to let users find friends and set up connections
- The social API can work with different providers, the demo websocket provider is a good simple one to get started/do testing (no account needed, single global user list) and you can switch later
- There's a tutorial in progress, feedback very welcome!

Hope this helps, and thanks for checking out our project.

**Comment by poshetz** [comment]
@soycode thank you a lot appreciated a lot! What i really can't get actually is how this could work on browsers like Safari which doesn't support webRTC, i see the demo chat is working over Safari, but i don't uderstand how since webRTC and peerConnections are disabled there... :)

Sorry for so many quesitons but it's just me trying to understand before to go for, your project is awesome.

**Comment by soycode** [comment]
@poshetz it looks like you're right, Safari doesn't support WebRTC. Wikipedia has a list of current compatibility: https://en.wikipedia.org/wiki/WebRTC#Support

It notes that support is possible in Internet Explorer and Safari via plugins, so you could point your users to those. I would also expect them to add WebRTC in the not-too-distant future (IE is working on a major rewrite/rebranding [codenamed Spartan](https://en.wikipedia.org/wiki/Spartan_(browser))).

But yes, getting peer to peer videochat working will require WebRTC support, so you should target that. Then freedom.js will help with signaling, and you can mostly focus on just writing a great usable app. This picture from the html5rocks.com tutorial linked above may clarify:

![JSEP Architecture](http://www.html5rocks.com/en/tutorials/webrtc/basics/jsep.png)

WebRTC handles the entire lower part (the blue boxes and media stream between them), and is built into (most and hopefully soon all) browsers, so you just have to make the appropriate calls to it. freedom.js and a social provider (like p2pbr.com) will fit in where that cloud is, helping the users signal each other. You have to write the green "app" box itself, as well as think about the arrows coming directly out of it (how to invoke freedom.js and WebRTC).

No worries on questions, we're happy to help people get started using our framework. I also suggest taking a look at the tutorial - it's in progress, but the initial sections already have some info about how to get set up developing with freedom.js. If you encounter questions or issues specific to it feel free to file issues in its repository. Thanks!

**Comment by poshetz** [comment]
@soycode  thank you so much! now it's more clear to me :+1:
