### ISSUE TITLE
demo module names not descriptive

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom#260]
`fredom-module.json` is a mouthful and hard to differentiate. We maybe should prefer using descriptive manifests named after the modules that are in the demos, like `counter.json` and `chat.json`. It helps make it clear which module is which when looking at web workers and logs.

**Comment by iislucas** [comment]
My experience in uproxy is that directory already names the functionality the freedom module json file is related to; we got more information by naming it `freedom-module.json` than anything else.

**Comment by soycode** [comment]
We chatted about this a bit yesterday, but I think that while maybe something like `freedom-module` makes sense for a large hierarchically organized project like uproxy, having a shorter more directly informative name is a better "suggested default" for most projects.
