### ISSUE TITLE
One-way void method calls for performance

### ISSUE THREAD

**Issue by bemasc** [freedomjs/freedom#271]
Prototype at https://github.com/freedomjs/freedom/tree/bemasc-oneway

Currently, every freedom module method call requires two IPCs, one for the call and one for the return value.  However, there are many cases where the caller of a method wishes to ignore the return value, and does not care to be notified after the method succeeds.  When these method calls are on a performance-critical path, the unnecessary response event can represent a significant inefficiency.

The above prototype, tested with uproxy-churn, increases throughput by ~12%.

TODO:
 * Figure out how to handle errors.
 * Determine an appropriate API.

**Comment by bemasc** [comment]
The prototype's current API is to add a new object type to the manifest called "voidMethod".  This was expedient to implement, but may not be a desirable end state.  An alternative proposal has been to choose a special value for "ret" such as `null` or `false`.

A different approach might be to define some sub-object that offers all the same methods, but with ignored return.  For example, `ignored = someProxy.method(arg)` would become `someProxy.withIgnoredReturn.method(arg)`.  This would have the advantage that the caller could choose whether to ignore the return of any method, at any callsite.  However, it would pollute the namespace of allowed methods.  Yet another option would be a static helper function like `freedom.noReturn(someProxy).method(arg)` or `freedom.noReturn(someProxy.method)(arg)`.

Suggestions appreciated; this is blocked until we resolve the design question.

**Comment by bemasc** [comment]
Some more design proposals based on a discussion with Lally:

Maybe we could have some kind of "flush" command that returns a promise that resolves when all the void messages ahead of it have been processed.  This could provide access to any errors that were generated by a void method, or even resolve with all the return values generated by non-void calls.  However, this seems to risk a memory leak.

One way to avoid the memory leak would be to stop all processing as soon as an error is encountered, and then have the flush method return only that error, possibly along with some indication of how many calls were successfully processed.  For example, each call could (synchronously, locally) return an incrementing sequence number, and then flush() could indicate which sequence number failed.

On the topic of spelling, one additional possibility would be to define `someProxy._` as a special namespace reserved by freedom, leading to a spelling like `someProxy._.void.method(arg)`.

**Comment by willscott** [comment]
The flush thing sounds like a level of complexity that very few people
would want to develop with / that would dramatically increase barrier of
entry.

We could also do
```javascript
someProxy.send.recklessly(blah,blah)
```

**Comment by mollyling** [comment]
At some point you'll want to know that the messages got processed by the other side, and it's how you encapsulate an async api inside of a synchronous one.  For example, say I want to issue a bunch of messages that modify a DOM tree.  I don't want to wait for each mutation.  Instead, I'd like to just issue them, do anything else I cared about, and then make sure that the changes are in before returning from my own promise.

**Comment by bemasc** [comment]
OK, I pushed a new version that implements @willscott's `.reckless` pattern.  Here's a pull request, just for discussion purposes:
https://github.com/freedomjs/freedom/pull/274
