### ISSUE TITLE
core.udpsocket::bind doesn't use its error codes

### ISSUE THREAD

**Issue by bemasc** [freedomjs/freedom#283]
The interface defines a bunch of error codes, but neither Chrome nor Firefox uses them in its implementation of bind().  Instead, they return an error code that is not even on the list!

**Comment by soycode** [comment]
To document a bit, the extant errcodes are:

    "ERRCODE": {"type": "constant", "value": {
      /** GENERAL **/
      "SUCCESS": "Success!",
      // Unknown
      "UNKNOWN": "Unknown error",
      
      // Socket is already bound
      "ALREADY_BOUND": "Socket already bound",
      // Invalid Argument, client error
      "INVALID_ARGUMENT": "Invalid argument",
      // Socket reset because of change in network state.
      "NETWORK_CHANGED": "Network changed",
      // Failure to send data
      "SNED_FAILED": "Send failed"
    }}

The actual providers in Chrome/Firefox use a fairly general BIND_FAILED, and Chrome also uses SOCKET_CLOSED while Firefox has INVALID_ARGUMENT (which is at least in the API). So, my plan:

- Add SOCKET_CLOSED
- Fix SNED_FAILED typo
- See if the BIND_FAILED uses can be made more specific, else add as well

**Comment by soycode** [comment]
What I actually did:

- Switched SOCKET_CLOSED to more relevant existing errcodes
- Changed BIND_FAILED to UNKNOWN (since that already exists and seems to have the same "we don't really know what happened" meaning)

Pull requests linked above by GitHub magic.
