### ISSUE TITLE
Change build process to support unicode

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom#287]
Right now we're explicitly restricting our code to ascii so sourcemaps work (see #286). When dependencies align happily, we should remove this restriction.

**Comment by willscott** [comment]
what needs to happen to do this?
would this be transform in browserify to just remove non-ascii characters?

**Comment by soycode** [comment]
Ideally the main thing to change on our end is just remove the `replace` task - I believe the issue is a bug propagating across various browserify related dependencies, and that with a bit of time it may just be resolved. That said, I'll check in on it periodically and if that's not happening then I'll revisit in more depth.

**Comment by soycode** [comment]
Periodic check, issue still live so keeping the `replace` task.

**Comment by soycode** [comment]
Issue still live - if I get a chance at this point I may look into fixing it upstream.
