### ISSUE TITLE
Documentation - wiki should line up with main API/behavior

### ISSUE THREAD

**Issue by agallant** [freedomjs/freedom#296]
This is a "meta" issue to track documenting freedom.js behavior. Right now there are significant aspects of freedom.js that are not explained on the wiki. For example, module cleanup/teardown: https://github.com/freedomjs/freedom/issues/295

Goals:
- Figure out what isn't documented, and at least stub out basic documentation for it
- Identify inconsistencies and gaps in both functionality and documentation
- Polish, and maybe publish to something besides the wiki (e.g. https://readthedocs.org/ http://readme.io/ etc/)

This is a bit separate from the tutorial, which is more of a "getting started"/basic freedom.js-consumer example - this documentation should ultimately be comprehensive and useful to developers that are going deep in freedom.js-land, not just using it externally.
## Linked-but-nonexistent wiki pages
- [x] [Tutorial: Cross Platform](https://github.com/freedomjs/freedom/wiki/Tutorial:-Cross-Platform)
- [x] [Existing API providers](https://github.com/freedomjs/freedom/wiki/Existing-API-Providers)
- [x] [Publishing freedom.js modules](https://github.com/freedomjs/freedom/wiki/Publishing-freedom.js-modules)
- [ ] [freedom.js structure: environment](https://github.com/freedomjs/freedom/wiki/freedom-structure-environment)
- [ ] [freedom.js structure: module](https://github.com/freedomjs/freedom/wiki/freedom-structure-module)
- [ ] [freedom.js structure - policy](https://github.com/freedomjs/freedom/wiki/freedom-structure-policy)
- [ ] [freedom.js structure - debug](https://github.com/freedomjs/freedom/wiki/freedom-structure-debug)
- [ ] [freedom.js structure - links](https://github.com/freedomjs/freedom/wiki/freedom-structure-links)
- [ ] [freedom.js structure - hub](https://github.com/freedomjs/freedom/wiki/freedom-structure-hub)
- [ ] [freedom.js structure - api](https://github.com/freedomjs/freedom/wiki/freedom-structure-api)
- [ ] [freedom.js.structure - packaging](https://github.com/freedomjs/freedom/wiki/freedom-structure-packaging)
## Existent-but-should-be-extended wiki pages
- [ ] [Common issues](https://github.com/freedomjs/freedom/wiki/Common-Issues)
- [ ] [Debugging](https://github.com/freedomjs/freedom/wiki/Debugging)
- [ ] [Provider Testing](https://github.com/freedomjs/freedom/wiki/Provider-Testing)
- [ ] [Logging](https://github.com/freedomjs/freedom/wiki/Logging)
- [ ] [Compiling freedom.js](https://github.com/freedomjs/freedom/wiki/Compiling-freedom.js) (specifically adding platform/flavor specific notes)
- [ ] [freedom,js structure](https://github.com/freedomjs/freedom/wiki/freedom.js-structure) and its subpages
- [ ] [Tutorial: View API](https://github.com/freedomjs/freedom/wiki/Tutorial:-View-API)

**Comment by soycode** [comment]
@willscott @ryscheng just giving you a heads up on this, my intent is to either complete articles or remove links to them. Since one of you presumably made the link(s) in the first place I may have questions about what you were envisioning as content - most of it is clear, but one in particular I'm unsure about is "Publishing" (linked to as "Publishing freedom.js" from the bottom of the main wiki). Do you just mean guidelines around releasing freedom.js-powered apps, or something about publishing freedom.js itself?

**Comment by willscott** [comment]
I think publishing apps / modules.
