### ISSUE TITLE
how to set up private signal server using node.js+socket.io

### ISSUE THREAD

**Issue by wei-jiang** [freedomjs/freedom#298]
I want to build social module's signal server into my node.js+express+socket.io website (not use official wss://p2pbr.com/route/).Is threre any guidance of this setup? or can each individual signalling server config to connect each other?

**Comment by willscott** [comment]
The social router code is here:
https://github.com/freedomjs/socialrouter

you can change the URL when you make the social provider to point to your
own URL.

The protocol is pretty simple, so you could make a compatible server if you
don't like python.

**Comment by wei-jiang** [comment]
Thanks a lot for the right direction.

**Comment by soycode** [comment]
Closing as I assume that repo helped you, but if you have any other questions feel free to ask. Thanks!
