### ISSUE TITLE
Fix integration tests post lazy module loading

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom#312]
Currently 12 integration tests fail - https://app.shippable.com/runs/5727d55199e6210c008cda93

It looks like errors often have to do with testing broken dependencies (https://github.com/freedomjs/freedom/blob/ead1ece1c47085d73214a02010a8d2af7ad00a3f/spec/helper/environment.js#L47) as well as timeouts, so possibly the new lazy approach is causing state to "leak" a bit across tests.

**Comment by soycode** [comment]
@bemasc I'm trying to debug this but curious on your thoughts/experience. Did/do these tests pass for you locally? I see you touched many of the related files, and while it looks like the tests you added pass several of the ones above it now seem to fail.

**Comment by bemasc** [comment]
Yep, grunt test passes locally with 296 SUCCESS and 106 SUCCESS.

**Comment by soycode** [comment]
Very odd - I get the same 12 failures as on Shippable, both natively on OSX and in an Ubuntu 14.04 VM. Travis looks to only be running the 150 unit tests and not the integration tests, and those all pass locally/on Shippable as well.

I'm generally testing in stable-or-newer node, Firefox, and Chrome - I assume you are as well, but if you happen to be running really old node or something let me know. Thanks.

**Comment by bemasc** [comment]
I'm using:
 * node 0.10.25
 * Firefox 46.0
 * Chromium 49.0.2623.108
 * Ubuntu 14.04
 * Fresh install of all npm dependencies

grunt test-phantom says
> PhantomJS 2.1.1 (Linux 0.0.0): Executed 148 of 150 (skipped 2) SUCCESS (0.848 secs / 0.844 secs)

**Comment by bemasc** [comment]
Solved.  I forgot to `git add` a new file.  :-(

**Comment by soycode** [comment]
No worries, thanks for catching!
