### ISSUE TITLE
Fix freedom.spec.js tests in Chrome 52+

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom#319]
For Chrome 52+ (52 will be the next release, 54 is current Canary), these tests fail:

Chrome 54.0.2795 (Mac OS X 10.11.5) freedom Handles manifest-defined APIs FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
Chrome 54.0.2795 (Mac OS X 10.11.5): Executed 17 of 150 (1 FAILED) (0 secs / 10.836 secs)
Firefox 44.0.0 (Mac OS X 10.11.0): Executed 148 of 150 (skipped 2) SUCCESS (1.95 secs / 1.916 secs)
Chrome 54.0.2795 (Mac OS X 10.11.5) WARN: 'waiting on internal channel for msg'
Chrome 54.0.2795 (Mac OS X 10.11.5): Executed 17 of 150 (1 FAILED) (0 secs / 10.836 secs)
Chrome 54.0.2795 (Mac OS X 10.11.5) freedom instances Supports custom loggers FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
Chrome 54.0.2795 (Mac OS X 10.11.5): Executed 18 of 150 (2 FAILED) (0 secs / 20.843 secs)
Firefox 44.0.0 (Mac OS X 10.11.0): Executed 148 of 150 (skipped 2) SUCCESS (1.95 secs / 1.916 secs)
Chrome 54.0.2795 (Mac OS X 10.11.5) ERROR: 'Provider does not implement m1()!'
Chrome 54.0.2795 (Mac OS X 10.11.5): Executed 49 of 150 (2 FAILED) (skipped 1) (0 secs / 21.006 secs)
Chrome 54.0.2795 (Mac OS X 10.11.5): Executed 94 of 150 (2 FAILED) (skipped 1) (0 secs / 21.025 secs)
Firefox 44.0.0 (Mac OS X 10.11.0): Executed 148 of 150 (skipped 2) SUCCESS (1.95 secs / 1.916 secs)
Chrome 54.0.2795 (Mac OS X 10.11.5) - freedom:
Chrome 54.0.2795 (Mac OS X 10.11.5) 	Handles manifest-defined APIs FAILED
Chrome 54.0.2795 (Mac OS X 10.11.5) WARN 'waiting on internal channel for msg'
Chrome 54.0.2795 (Mac OS X 10.11.5)
Chrome 54.0.2795 (Mac OS X 10.11.5) - freedom instances:
Chrome 54.0.2795 (Mac OS X 10.11.5) 	Supports custom loggers FAILED

The tests:
- https://github.com/freedomjs/freedom/blob/master/spec/src/freedom.spec.js#L43
- https://github.com/freedomjs/freedom/blob/master/spec/src/freedom.spec.js#L73

The other tests pass, so whatever it is it's not breaking all message passing. Most likely it's this helper that both depend on - https://github.com/freedomjs/freedom/blob/master/spec/helper/logger.js

Possibly useful is a list of all changes between Chrome 51 and 52 (big page, long load) - https://chromium.googlesource.com/chromium/src/+log/51.0.2704.103..52.0.2743.75?pretty=fuller&n=10000

**Comment by soycode** [comment]
After some logging, the main difference for these tests between Chrome 51 and 52 is that the former emits *two* "default" messages (I believe for module setup) to moduleinternal, while the latter only emits one. I think two is what we want because the module (logger.js) provides two things (console and getLogs).

I'm not sure this is the issue though, because there's a demo that uses a similar logging module w/two providers (http://www.freedomjs.org/dist/freedom/latest/demo/advancedlogging/) that seems to work in Chrome canary. So, while it is something about these "default" messages, it could potentially be the app.js module and not the logger.js module that is the problem.

**Comment by soycode** [comment]
It is hanging out the `JSON.stringify` call - https://github.com/freedomjs/freedom/blob/master/spec/helper/logger.js#L36

That is, Chrome 52+ fails to return when `JSON.stringify` is called in this freedom module. Moving the calls to a different method (e.g. maintaining a `qstring` variable and trying to update it with `JSON.stringify` in the actual logging calls) leads to the same result.

This could well be an actual Chrome bug - `JSON.stringify` still exists and works interactively in the console, so it may be WebWorker specific. This looks like the potentially most relevant commit - https://chromium.googlesource.com/chromium/src/+/1a5019c2282bbbd1a69c266c0e9b2e237caa234c

For now though I may tweak the test to use `.toString` and `.split` so it works for now, since it's basically a private util hack regardless.

**Comment by willscott** [comment]
I don't see it getting that far. A log in the 'GetLogs' constructor doesn't seem to fire. It seems like the request to create the API provider instance is never happening.

**Comment by soycode** [comment]
I added logging where actual module resources are loaded (https://github.com/freedomjs/freedom/compare/soycode-testlogging). It seems like the logger.json manifest is at least being loaded the same number of times as in Firefox. So, may happen after resource loading but before the GetLogs constructor is properly set up.

**Comment by soycode** [comment]
Tried following module/manifest loading until I saw a difference between Chrome and Firefox, and was able to find one in `Policy.get`:

Logging statements: https://github.com/freedomjs/freedom/commit/78ae9c663d46c2fb81f92784e1e42b647c919bd9

Firefox behavior:

    Firefox 48.0.0 (Ubuntu 0.0.0) LOG 'else http://localhost:9876/spec/helper/manifest.json'
    Firefox 48.0.0 (Ubuntu 0.0.0) LOG 'else http://localhost:9876/spec/helper/logger.json'
    Firefox 48.0.0 (Ubuntu 0.0.0) LOG 'topif http://localhost:9876/spec/helper/logger.json0.07051834751934505'
    Firefox 48.0.0 (Ubuntu 0.0.0) 	Handles manifest-defined APIs PASSED

Chrome behavior:

    Chrome 52.0.2743 (Linux 0.0.0) LOG 'else http://localhost:9876/spec/helper/manifest.json'
    Chrome 52.0.2743 (Linux 0.0.0) LOG 'else http://localhost:9876/spec/helper/logger.json'
    Chrome 52.0.2743 (Linux 0.0.0) freedom Handles manifest-defined APIs FAILED
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

This suggests that `this.isRunning` is not returning (or not returning as expected) for Chrome in this particular situation. It may relate to the manager part as well, since that seems to be what dictates what is running.

**Comment by soycode** [comment]
Narrowed it down to `xhrRetriever`, which usually receives three `readystatechange` events when loading a manifest, but for the second needed `logger.json` load in Chrome for these tests it only receives one such event and then waits until test timeout. https://github.com/freedomjs/freedom/blob/soycode-testlogging/src/resource.js#L342

The method is a fairly minimal wrapper around `XMLHttpRequest`, so it seems that somehow Chrome behavior with XHR changed. I'll peruse the Chrome changelist I linked in the initial issue description again to see if I can find more specifics, but it is odd that it only seems to manifest when trying to load the same manifest a second time (for a second provided API).

**Comment by soycode** [comment]
The good news is I figured out a fix (making xhrRetriever synchronous - https://github.com/freedomjs/freedom/pull/322/commits/899fb41c3681de1d7abb29a5100228b18496d4e5).

The bad news is other tests have since regressed (looks like RTC-related integration tests). So, I'll keep this issue open to debug those...
