### ISSUE TITLE
It's not an issue, I just don't know what to do

### ISSUE THREAD

**Issue by rafaeldcastro** [freedomjs/freedom#333]
I'm developing an app where users can gather on a room and use P2P interactions with Wifi/ blutooth, etc

Using the app, one of the users (master) will send to the others a message, but its more like a warning or a tip. Sending an image from the app itself should trigger the receiver user to show the same image stored within his app.

I don't know if its possible to do this with Freedom.js

I run into the language problem (english is not my mother lang) and have difficulty understanding the instructions. I just want to know if it's possible, because I do not want to struggle in vain.

Thanks for your attention!

**Comment by willscott** [comment]
I don't think this is going to be easy to do with freedom.js

We don't have any support for wifi/bluetooth at this point, and would
require online connectivity against the public Internet.

**Comment by rafaeldcastro** [comment]
Hmm.. thx Will :D
Save me a lot of trouble
Anyway Freedom.js is a great work, and I will use it in other applications 
o/
Thanks again
